# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gmail-mailer}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Harper"]
  s.date = %q{2011-01-14}
  s.description = %q{Programatically send emails using a given gmail account. No username/passwords needed, just use your OAUTH credentials}
  s.email = %q{djharperuk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Changelog.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "gmail-mailer.gemspec",
    "lib/gmail-mailer.rb",
    "test/files/email_conf",
    "test/mail_test_send.rb",
    "test/test_mailer.rb",
    "test/test_message.rb"
  ]
  s.homepage = %q{http://github.com/djhworld/gmail-mailer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Send emails using a your gmail account (via OAUTH)}
  s.test_files = [
    "test/mail_test_send.rb",
    "test/test_mailer.rb",
    "test/test_message.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<mail>, ["~> 2.2.14"])
      s.add_development_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.2.14"])
      s.add_runtime_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<mail>, ["~> 2.2.14"])
      s.add_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
      s.add_dependency(%q<mail>, ["~> 2.2.14"])
      s.add_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<mail>, ["~> 2.2.14"])
    s.add_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
    s.add_dependency(%q<mail>, ["~> 2.2.14"])
    s.add_dependency(%q<gmail_xoauth>, ["~> 0.3.0"])
  end
end

